### ISSUE TITLE
Repair kits are extremely undervalued

### ISSUE THREAD

**Issue by Two-Tone** [Acruid/RepairBench#1]
Each kit costs 5 steel and 5 cloth to create, but is only valued at $3.50.  The value of the raw resources alone $17.  This leads to absurd quests such as the one below:

![image](https://user-images.githubusercontent.com/4342859/92375739-2483d880-f0c7-11ea-8f72-3f7f2d335410.png)

For reference, the raw resources needed for that quest is 4.2k steel and 4.2k cloth, valued at $14,280.  A value of $25 is much more balanced and won't lead to quests that cost so much

**Comment by Acruid** [comment]
Resolved in f786019826d5d9bb5abaecf9612fb925bb67da22. The game calculates the new price to be $18/kit, $17 for mats and $1 for crafting time.
